#!/usr/bin/env node
/**
 * Build per-platform MAIN-world overlay scripts from src/*-main/ directories.
 *
 * Each directory becomes public/{dir}.js (e.g. src/bm-main -> public/bm-main.js).
 * Modules inside a directory are concatenated in sorted order and wrapped in
 * an IIFE with a per-directory injection guard.
 */
const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const SRC_ROOT = path.join(ROOT_DIR, 'src');
const PUBLIC_DIR = path.join(ROOT_DIR, 'public');

function buildPlatformMain(dirName) {
  const srcDir = path.join(SRC_ROOT, dirName);
  const outFile = path.join(PUBLIC_DIR, `${dirName}.js`);

  const files = fs.readdirSync(srcDir)
    .filter(f => f.endsWith('.js'))
    .sort();

  if (files.length === 0) {
    console.error(`No module files found in ${srcDir}`);
    return false;
  }

  const modules = files.map(f => {
    const content = fs.readFileSync(path.join(srcDir, f), 'utf8');
    return `// ── ${f} ──\n${content}`;
  });

  const guardVar = `__miaosha_${dirName.replace(/-/g, '_')}_injected`;
  const output = `// MAIN world script — ${dirName}
// AUTO-GENERATED by scripts/build-overlay.js — DO NOT EDIT DIRECTLY
(function() {
  if (window['${guardVar}']) return;
  window['${guardVar}'] = true;

${modules.join('\n\n')}

})();
`;

  fs.writeFileSync(outFile, output, 'utf8');
  console.log(`Built ${outFile} from ${files.length} modules (${(output.length / 1024).toFixed(1)}KB)`);
  return true;
}

function main() {
  if (!fs.existsSync(PUBLIC_DIR)) {
    fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  }

  const entries = fs.readdirSync(SRC_ROOT, { withFileTypes: true });
  const platformDirs = entries
    .filter(e => e.isDirectory() && e.name.endsWith('-main'))
    .map(e => e.name)
    .sort();

  if (platformDirs.length === 0) {
    console.error('No src/*-main directories found');
    process.exit(1);
  }

  let built = 0;
  for (const dir of platformDirs) {
    if (buildPlatformMain(dir)) built++;
  }

  console.log(`Built ${built} platform MAIN-world script(s)`);
}

main();
